export enum E_Briefing_Type {
  ITINERARIOS = 'PLACA DE ITINERÁRIOS',
  SINALIZACAO_INTERNA = 'PLACA DE SINALIZAÇÃO INTERNA',
  ADESIVOS = 'ADESIVOS',
  IMPRESSOS = 'IMPRESSOS',
  LAYOUTS_PARA_BRINDES = 'LAYOUTS PARA BRINDES',
  CAMPANHAS_INTERNAS = 'CAMPANHAS INTERNAS',
  COMUNICADOS = 'COMUNICADOS',
}
